version: '3'
services:
  subscribe-xxx:
    image: ipc-subscriber
    restart: 'always'
    environment:
    - TZ=Asia/Taipei
    - MQTT_SERVER="10.1.64.30"
    - MQTT_PORT="33306"
    - MQTT_ALIVE=60
    - MQTT_TOPIC="/L1_PD1"
    - NFS_SERVER="10.1.64.30"
    - NFS_PORT=32222
    # - USER="models"
    # - PASSWD="liteonmodels"
    - LOCAL_PATH=/model
    volumes:
    - /home/aitest/model:/model
